task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  matrix:
    - name: Python formatting
      container:
        image: cytopia/black
      install_script: apk add git
      test_script: git ls-files -z -- ':!:test/cases' '**/*.py' | xargs -0 -- python3 -m black && git diff --exit-code
