task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  matrix:

    - name: FreeBSD
      freebsd_instance:
        image_family: freebsd-14-0-snap
      environment:
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: pkg upgrade -y && pkg install -y bash cmake git llvm py39-pytest vim
      test_script: ./misc/ci.sh

    - name: Linux
      container:
        image: gcc:12.1
      environment:
        DEBIAN_FRONTEND: noninteractive
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        LC_ALL: C.UTF-8
        PATH: /opt/cmake-3.21.1-linux-x86_64/bin:${PATH}
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y libclang-dev llvm python3-pytest sqlite3 xxd vim && wget https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz && mkdir -p /opt && tar xvf cmake-3.21.1-linux-x86_64.tar.gz --directory /opt
      test_script: ./misc/ci.sh

    - name: Linux, release build
      container:
        image: gcc:12.1
      environment:
        DEBIAN_FRONTEND: noninteractive
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        CMAKE_BUILD_TYPE: Release
        LC_ALL: C.UTF-8
        PATH: /opt/cmake-3.21.1-linux-x86_64/bin:${PATH}
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y libclang-dev llvm python3-pytest sqlite3 xxd vim && wget https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz && mkdir -p /opt && tar xvf cmake-3.21.1-linux-x86_64.tar.gz --directory /opt
      test_script: ./misc/ci.sh

    - name: macOS
      osx_instance:
        image: monterey-xcode-13.3
      environment:
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
        PATH: /usr/local/opt/llvm/bin:${PATH}
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: brew update && brew install llvm && pip3 install pytest
      test_script: ./misc/ci.sh

    - name: C formatting
      container:
        image: silkeh/clang:14
      test_script: git ls-files -z -- ':!:test/cases' '**/*.c' '**/*.h' | xargs -0 -- clang-format --dry-run --style=file --Werror

    - name: Python formatting
      container:
        image: cytopia/black
      install_script: apk add git
      test_script: git ls-files -z -- ':!:test/cases' '**/*.py' | xargs -0 -- python3 -m black && git diff --exit-code
