task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  matrix:

    - name: FreeBSD
      freebsd_instance:
        image_family: freebsd-14-0-snap
      environment:
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
        CTEST_OUTPUT_ON_FAILURE: 1
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: pkg upgrade -y && pkg install -y cmake llvm vim

    - name: Linux
      container:
        image: gcc:11.3
      environment:
        DEBIAN_FRONTEND: noninteractive
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        CTEST_OUTPUT_ON_FAILURE: 1
        PATH: /opt/cmake-3.21.1-linux-x86_64/bin:${PATH}
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y libclang-dev llvm xxd && wget https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz && mkdir -p /opt && tar xvf cmake-3.21.1-linux-x86_64.tar.gz --directory /opt

    - name: macOS
      osx_instance:
        image: catalina-xcode-12.1
      environment:
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
        CTEST_OUTPUT_ON_FAILURE: 1
        PATH: /usr/local/opt/llvm/bin:${PATH}
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: brew update && brew install llvm

  test_script: uname -sr && mkdir build && cd build && cmake .. && cmake --build . && cmake --build . -- test && cmake --build . -- install
