task:

  # only test the main branch and pull requests
  only_if: $CIRRUS_BRANCH == "main" || $CIRRUS_PR != ""

  matrix:

    - name: FreeBSD
      freebsd_instance:
        image_family: freebsd-15-0-snap
      environment:
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: pkg upgrade -y && pkg install -y bash cmake cscope git llvm py311-pytest vim
      test_script: ./misc/ci.sh

    - name: Linux
      container:
        image: gcc:15.1
      environment:
        DEBIAN_FRONTEND: noninteractive
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        LC_ALL: C.UTF-8
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y cmake cscope libclang-dev llvm python3-pytest sqlite3 xxd vim
      test_script: ./misc/ci.sh

    - name: Linux, release build
      container:
        image: gcc:15.1
      environment:
        DEBIAN_FRONTEND: noninteractive
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined -fuse-ld=gold
        CMAKE_FLAGS: -DCMAKE_BUILD_TYPE=Release
        LC_ALL: C.UTF-8
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: apt-get update -y && apt-get install --no-install-recommends -y cmake cscope libclang-dev llvm python3-pytest sqlite3 xxd vim
      test_script: ./misc/ci.sh

    - name: macOS
      macos_instance:
        image: ghcr.io/cirruslabs/macos-sonoma-base:latest
      environment:
        CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=undefined
        PATH: /opt/homebrew/opt/llvm/bin:${PATH}
        UBSAN_OPTIONS: print_stacktrace=1
      install_script: brew update && brew install coreutils cscope llvm && python3 -m pip install --break-system-packages pytest
      test_script: env CMAKE_FLAGS=-DPython3_EXECUTABLE=$(which python3) ./misc/ci.sh

    - name: C formatting
      container:
        image: silkeh/clang:15
      install_script: apt-get update -y && apt-get install --no-install-recommends -y git
      test_script: clang-format --version && git ls-files -z -- ':!:test/cases' '**/*.c' '**/*.h' | xargs -0 -- clang-format --dry-run --style=file --Werror

    - name: Python formatting
      container:
        image: cytopia/black
      install_script: apk add git
      test_script: git ls-files -z -- ':!:test/cases' '**/*.py' | xargs -0 -- python3 -m black && git diff --exit-code
