.TH CLINK 1
.SH NAME
clink \- C/C++/assembly code navigator
.SH SYNOPSIS
.B \fBclink\fR \fIoptions...\fR [\fIpaths...\fR]
.SH DESCRIPTION
Clink is a replacement for Cscope that uses libclang, features syntax
highlighting, multicore support, and more.
.SH OPTIONS
\fB--build-only\fR, \fB-b\fR
.RS
Exit after constructing or updating the symbol database. That is, do not load a
user interface.
.RE
.PP
\fB--colour\fR \fIwhen\fR, \fB--color\fR \fIwhen\fR
.RS
Enable or disable the use of ANSI colour codes. Possible values of \fIwhen\fR
are "always" (enable), "never" (disable), and "auto" (decide based on whether
stdout is a TTY).
.RE
.PP
\fB--database\fR \fIFILE\fR, \fB-f\fR \fIFILE\fR
.RS
Open or create the symbol database at path \fIFILE\fR. Without this option,
Clink will default to opening the file .clink.db in the current directory or any
parent thereof if it exists. If none of these exist, Clink will fallback
to .clink.db in the current directory.
.RE
.PP
\fB--debug\fR
.RS
Enable Clink debugging mode. This is intended for debugging problems within
Clink itself.
.RE
.PP
\fB--help\fR, \fB-h\fR
.RS
Display this help information.
.RE
.PP
\fB--include\fR \fIPATH\fR, \fB-I\fR \fIPATH\fR
.RS
Include the given directory in the search path for C/C++ #includes. By default,
the list of include paths is your compiler's default.
.RE
.PP
\fB--jobs\fR \fINUM\fR, \fB-j\fR \fINUM\fR
.RS
Use the given number of threads when performing multithreaded operations. You
can also pass the special value "auto" (the default) which uses the number of
processors in your system.
.RE
.PP
\fB-l\fR
.RS
Use the line-oriented interface instead of the NCurses-based interface. The
line-oriented interface mimics Cscope's behavior just enough to feed Vim the
information it needs. It is missing all other functions and is not intended for
interactive use by a human.
.RE
.PP
\fB--no-build\fR, \fB-d\fR
.RS
Do not update the database.
.RE
.PP
\fB-s\fR \fIPATH\fR
.RS
Add the given path to the list to search for files to index. This has the same
effect as including the \fIPATH\fR standalone at the end of your Clink
invocation; the \fB-s\fR option is only provided for backwards compatibility
with Cscope.
.RE
.SH AUTHOR
All comments, questions and complaints should be directed to Matthew Fernandez
<matthew.fernandez@gmail.com>.
.SH LICENSE
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org>
