name: Github Actions CI
permissions: {}
on:
  pull_request:
    branches:
      - main
jobs:
  freebsd15:
    name: FreeBSD 15.0
    runs-on: ubuntu-24.04
    steps:
    - uses: vmactions/freebsd-vm@7ca82f79fe3078fecded6d3a2bff094995447bbd
      with:
        sync: no
        release: "15.0"
        usesh: true
        run: |
          set -e
          set -o pipefail
          set -u
          set -x
          uname -rms
          pkg install -y bash cmake cscope git llvm python3 devel/py-pytest sqlite3 databases/py-sqlite3 vim
          python3 --version
          git clone --no-checkout --recurse-submodules -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
          cd wd
          git fetch -- origin ${{ github.event.pull_request.head.sha }}
          git checkout FETCH_HEAD
          git submodule init
          git submodule update
          export CFLAGS="-Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=address,undefined"
          export UBSAN_OPTIONS=print_stacktrace=1
          export TERM=xterm
          cmake -B build -S .
          cmake --build build
          cmake --build build --target check
          printf "find-me says: "
          ./build/test/find-me/find-me
          cmake --install build

  macos26:
    name: macOS
    runs-on: macos-26-intel
    env:
      CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=address,undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: python3 --version
      - run: brew update
      - run: brew install coreutils cscope llvm
      - run: env PIP_BREAK_SYSTEM_PACKAGES=1 python3 -m pip install pytest
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout --recurse-submodules -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: >
          cd wd &&
          git fetch -- origin ${{ github.event.pull_request.head.sha }} &&
          git checkout FETCH_HEAD &&
          ./misc/ci.sh

  ubuntu2604:
    name: Linux
    runs-on: ubuntu-26.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=address,undefined
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y cscope libclang-dev llvm python3-pytest xxd vim
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout --recurse-submodules -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: >
          cd wd &&
          git fetch -- origin ${{ github.event.pull_request.head.sha }} &&
          git checkout FETCH_HEAD &&
          ./misc/ci.sh

  ubuntu2604_release:
    name: Linux, release build
    runs-on: ubuntu-26.04
    env:
      DEBIAN_FRONTEND: noninteractive
      CFLAGS: -Werror -g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=address,undefined
      CMAKE_FLAGS: -DCMAKE_BUILD_TYPE=Release
      UBSAN_OPTIONS: print_stacktrace=1
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y cscope libclang-dev llvm python3-pytest xxd vim
      - run: echo "cloning ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
      - run: git clone --no-checkout --recurse-submodules -- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} wd
      - run: >
          cd wd &&
          git fetch -- origin ${{ github.event.pull_request.head.sha }} &&
          git checkout FETCH_HEAD &&
          ./misc/ci.sh
